ACCOUNTS="GCOHQFQZZPCRV74BU5PCMCMGIQYI4XSV5NXI5LZS3J53L7HMVSQHVTHD"
SQ02_EASTER_EGG = "With all the wheezing of a dying amoeba, the blue-garbed Stroopy grunted and heaved at the towering behemoth that was his desk. He should have used the TRAs leftover to hire somebody to bring in the desk for him, but figured the money should go towards a better cause – his stomach.

Regretting his decision to get the wiggly noodles, Stroopy pressed his back against the crate and shoved one more time. The crate breached the entrance of his office, and he slid down to the floor in pyrrhic victory. Sweet Solarus he was exhausted.

It all started when he woke up five hours too early at the sound of someone furiously pounding at his door. With a rare stroke of premonition, he opened the door and managed to escape the initial barrage of expletives delivered by a red-faced Rabelais with strategically placed earmuffs.

After he finally managed to get a word in (“Rabs, I asked Grimm for a ‘loan!’ L - O - A - N. It means I’m going to pay him back!” he shouted, fending off her frightful visage with an oven mitt), the two longtime friends settled into more civil discussion.

“Rabs, I know you mean best for Grimm, but he can take care of himself,” Stroopy said, wiping off the egg dripping down the wall. “Was it really necessary for you to come all the way to Sol III to defend his honor? He’s not some damoiseau in distress.”

Rabelais huffed, She was sitting in his sagging office chair, spinning herself in idle circles. “You know just as well as I do that Grimm hates confrontation. And office furniture is expensive! Do you know how much exotic contraband I’ve had to confiscate from all the grubs and young’ns this past year?”

“A lot?”

“Yes,” she deadpanned, “a lot.”

Despite her overeagerness to get into a scuffle, Stroopy appreciated her forthright demeanor and willingness to stick up for those who needed a voice the most, no matter how loud. Plus, it was amusing to tease her and see her face swell up like the red balloons that so often filled the sky at RisaVale. Hotheaded indeed.

Rabelais finally departed, absconding with the pamphlet that the Sender had sent him. “Huh. They didn’t do a bad job portraying me here,” she preened, satisfied with the artist’s high opinion of her character. Stroopy didn’t have the heart to tell her that to tell her that extensive dramatic license wasn’t always a good thing.

Wearied by the tribulations of Rabelais in the morning and moving the desk in the afternoon, Stroopy did the only thing he could do and flop on the gritty floor, nursing a drink of his own design – the Stroop Spritz.

Thumbing at his phone, he decided to shoot an email to the Sender.

It was nice to have a pen pal in someone like the Sender, he thought, a being so completely separated from the everyday going-ons that their psyche was unbothered by the trivialities of daily life. Was this what it was like to be a deity? To be able to observe the events of the universe with the full knowledge that, boom or bust, nothing would affect you at all? Did the Sender find its situation comforting or lonely? Why did it have such a vested interest in life forms that it would never meet, whose life spans would whittle down to nothing more than a speck in the ever-expanding cosmos? And how was Sasara doing, the best of girls?

The email went on for longer than he anticipated, but Stroopy figured that the Sender had all the time in the world. Surely it had time to also play psychoanalyst to his growing existential anxiety. He clicked send.

RECIPIENT SERVER DID NOT ACCEPT OUR REQUEST.

He groaned. What was the point of setting up an email address if there remained some impenetrable cosmic firewall around one’s inbox? Stumbling to his feet, he went off to find some ink and paper, write a letter, and build the desk in no particular order.
"